### ISSUE TITLE
Haskell-1/Application/01-HelpHass/ train shedule

### ISSUE THREAD

**Issue by lolotobg** [HackBulgaria/Haskell-1#2]
One question regarding something that I didn't understand clearly from the tasks description:

Are the trains supposed to depart exactly when Hass arrives at the station (enters the train) i.e. they have no shedule like:

If there are trains A -> B, B -> C, C -> D, we assume that A -> D always takes 15 minutes (5 minutes each ride) so there isn't any transfer time/waiting on the stations?

**Comment by dtaskoff** [comment]
We assume, that the trains will be waiting for Hass. As you said above - A -> D will always take 15 minutes :)
