### ISSUE TITLE
Haskell-1/Application/02-LanguageCame/ character number of repeats

### ISSUE THREAD

**Issue by lolotobg** [HackBulgaria/Haskell-1#3]
A question regarding the tasks description:

Is the part "^n" always constant - the characters always repeat one and the same number of times?

Is the language "a^nb^Mc^n" valid and with meaning "one character repeated X times, a different character repeated Y times and a third character (not equal to either of the first two) repeated X time again" where X and Y are arbitary but different natural numbers (without the 0)?

**Comment by dtaskoff** [comment]
Yes, the part '^n' is always constant and the word you mentioned is not from the language :)
